// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwAw2JAGFeiZU6LwqYXEic2X2YCVdTwYg',
    appId: '1:951219876292:web:078700c8c82b8e439b3491',
    messagingSenderId: '951219876292',
    projectId: 'flash-chat-77520',
    authDomain: 'flash-chat-77520.firebaseapp.com',
    storageBucket: 'flash-chat-77520.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQwhosRSc-PpDk4ESFF_aXwmVhagAwdg',
    appId: '1:951219876292:android:4339c5d1daa99f689b3491',
    messagingSenderId: '951219876292',
    projectId: 'flash-chat-77520',
    storageBucket: 'flash-chat-77520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYDwNQNf96AE-GOTSRVw1szZBmx5JQsdc',
    appId: '1:951219876292:ios:72254d0b0020a67e9b3491',
    messagingSenderId: '951219876292',
    projectId: 'flash-chat-77520',
    storageBucket: 'flash-chat-77520.appspot.com',
    iosClientId: '951219876292-kaqp02dhc93vfl85bf32a2o516rjftsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYDwNQNf96AE-GOTSRVw1szZBmx5JQsdc',
    appId: '1:951219876292:ios:4dd7fcddfa688da39b3491',
    messagingSenderId: '951219876292',
    projectId: 'flash-chat-77520',
    storageBucket: 'flash-chat-77520.appspot.com',
    iosClientId: '951219876292-8def0nht7serh73jj28hvvgi963t291k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter.RunnerTests',
  );
}
